---
title: "Productivity in the Workplace"
---

Productivity in the workplace is influenced by decisions that are made by management - not decisions that are made by workers. Investment in physical capital, like tools and machines, new technologies, and investment decisions are made by management. These decisions directly impact productivity. Well maintained modern machinery which is well maintained, will improve the workers output.

Worker health is another important determinant of productivity. A healthy workforce is a more productive workforce. This includes sufficient rest between and within a shift, as well as sufficient time off for leisure. While workers have some control over their own health, sufficient time off to rest and recover is dependent on whether wages provide a minimum standard of living. If wages aren't high enough, workers are forced to work overtime, take extra shifts, or pick up a second job to survive. All at the expense of leisure and rest time.

There are other determinants of worker health that are not controlled by individual workers, such as the maintenance of a safe workplace - both physically and psychosocially.

A skilled workforce is a more productive workforce. But the ability to undertake training is also dependent on wages or other decisions of management. Workers should not be required to use their leave - paid or otherwise - to undertake training. Especially if there is no likelihood of increased pay in recognition of that training. The labour market in Australia is highly concentrated and workers are already underpaid relative to their skills.

So, when they say it is up to the worker to offer improvements to labour productivity, it is important to remember that ***productivity in the workplace is shaped by the choices companies make***. As workers, our offer for improvements to labour productivity should always include increased wages and greater control over our work and the decisions made about it.
