project:
  type: website
  resources: 
        - productivity-single.pdf
  preview: 
    port: 4200
    browser: false
website:
  title: "AMWU Member Portal"
  navbar:
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Economics and Political Economy"
        href: productivity.qmd
      - text: "Presentations"
        href: presentations.qmd
        
  sidebar:
    - title: "Economics and Political Economy"
      style: "docked"
      contents:
        - productivity.qmd
        - inflation.qmd
        - political-economy.qmd


format:
  html:
    bibliography: references.bib
    fig-format: svg
    fig-width: 8
    fig-asp: 0.618
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
  typst:
    logo:
      location: right-top
      padding-right: 1.5cm
      padding-bottom: 3cm
      padding-top: 1.5cm
    fig-format: svg
    fig-width: 8
    fig-asp: 0.618


editor: visual
execute: 
  echo: false
  warning: false
  message: false
  
brand:  _extensions/amwu-nrc/amwu-brand/brand.yml

