project:
  type: website
  preview: 
    port: 4200
    browser: false
website:
  title: "Blog"
  description: "Website Description"
  page-navigation: true
  navbar:
    pinned: true
    left:
      - text: "Economics and Political Economy"
        file: index.qmd
      - text: "Presentations"
        href: presentations.qmd
        
  sidebar:
    - title: "Economics and Political Economy"
      style: "docked"
      contents:
        - text: Economics and Political Economy
          file: index.qmd
        - section: Productivity
          contents:
            - text: Summary
              file: sections/productivity/productivity-summary.qmd
            - text: Productivity Definition
              file: sections/productivity/productivity-definition.qmd
            - text: Productivity Trends
              file: sections/productivity/productivity-trends.qmd
            - text: Productivity and Wages
              file: sections/productivity/productivity-wages.qmd
            - text: Productivity in the Workplace
              file: sections/productivity/productivity-work.qmd
        - section: Inflation
          contents:
            - text: Inflation Summary
              file: sections/inflation/inflation-summary.qmd
            - text: Inflation Definition
              file: sections/inflation/inflation-definition.qmd
            - text: Inflation Trends
              file: sections/inflation/inflation-trends.qmd
            - text: Inflation and the Cost of Living
              file: sections/inflation/inflation-cost-of-living.qmd
            - text: Inflation and Wages
              file: sections/inflation/inflation-wages.qmd
        - section: Political Economy
          contents:
          - sections/political-economy/political-economy.qmd
bibliography: 
    - references.bib
format:
  html:
    fig-format: svg
    fig-width: 8
    fig-asp: 0.618
    theme:
      - brand
    css: styles.css
    toc: true

editor: visual
execute: 
  echo: false
  warning: false
  message: false
  
brand:  _extensions/amwu-nrc/amwu-brand/brand.yml
brand-mode: light

