# Summary

Inflation has been a hot topic with cost of living increases, and interest rate decisions. Under neo-liberalism, inflation has become the single most important economic priority, coinciding with the increased dominance and "importance" of the financial industry and financial capital at the expense of productive industries like manufacturing.

Controlling inflation is seen as a more important policy goal than:

-   full employment

-   reducing inequality

-   housing affordability

-   alleviating poverty.

Instead of full employment, government and institutions now push the "non-accelerating inflation rate of unemployment" which suggests there is a minimum level of unemployment necessary in order to stop wages growth and rising inflation. Of course, we can't measure the NAIRU, only show that it might exist, if a bunch of assumptions are made about how the economy works. Estimates from data suggest that it falls somewhere between 4 and 5%.

This means that it is explicit government policy to keep up-to 5% of the labour force out of work, in order to keep inflation down.

Such policy might be palatable if there was a strong social safety net to support workers who lose their job and are looking for another one. Of course, we don't even get that, with only the below poverty JobSeeker payment available.

But it is still a very inefficient use of the labour power that our economy has access to. Why shouldn't someone who wants to work not have access to a job? It also means that policy is designed to discipline labour.

Which by the way, is why the budget in 2024, by the nominative party of labour, forecast that the plan was to tackle inflation by driving the unemployment rate UP to at least 4.5 percent by June 2025. Cold comfort for those who find themselves unemployed.
